### ISSUE TITLE
Confused about a few locations

### ISSUE THREAD

**Issue by captncraig** [MrCheeze/botw-tools#4]
I'm trying to scrape out location data for some work I'm doing on [this save editor](https://github.com/marcrobledo/savegame-editors/tree/master/zelda-botw).

The approach I'm taking is this:
1. Start with 187 known save file hashes for discoverable locations.
2. Find hash in [`gamedata/s32_data_0.xml`](https://github.com/MrCheeze/botw-tools/blob/master/gamedata/s32_data_0.xml#L7453)
3. Cross reference with values pulled out of `mubin` directory with matching `SaveFlag` value, to find location.

Doing this gives me locations for 182 out of 187 locations. The ones that I'm missing are:

```
Location_UMiiVillageShopYadoya
Location_UMiiVillageShopYorozu
Location_UMiiVillageShopJewel
Location_UMiiVillageShopBougu
Location_HyruleGround
```

I'm having a hard time finding what/where those are, and am having trouble correlating with your other repo, or finding locations with grep. Those particular strings are not anywhere in the mubin dir, but all other location names are. Am I taking a really bad approach to this, or is there maybe something wrong with the data?

**Comment by EnsignR** [comment]
I am similarly confused. I've been searching your data trying to categorically prove one way or the other if you can somehow register and keep the Lord of the Mountain or not. Personally I can't believe they put all the effort into making him, put you though all the effort to get him and yet he's basically useless.

I've been searching all the data looking for references to Lord or Nushi etc and not having any luck.

Then I tried something else.

If you talk to Bolson without a shirt on he says something like "You're looking perky". So I've searched the entire dump for the text string "perky". No dice. It's not there.

I've got a couple of theories as to why, but rather than theorise without anything to back it up I'd really like to know how you got all this data.

Thanks

**Comment by MrCheeze** [comment]
Hyrule Ground = the "hyrule kingdom" text that appears when you leave the plateau. It has no other significance.

UMiixxx = the various shops that pop up in Tarrey Town. These are the only building icons that show up only partway through the game.

All of these are special cases of sorts.


You can't register GameRomHorseNushi, but you can edit your save so that an existing stored horse is this actor, possibly.
